# Basic dependabot.yml file with minimum configuration for gomod.

version: 2
updates:
  # Enable version updates for netmaker
  - package-ecosystem: "gomod"
    directory: "/"
    # Check for updates every day (weekdays)
    schedule:
      interval: "weekly"
    target-branch: "develop"
  # Enable version updates for netclient
  - package-ecosystem: "gomod"
    directory: "/netclient"
    # Check for updates every day (weekdays)
    schedule:
      interval: "weekly"
    target-branch: "develop"
  # Enable version updates for GitHubActions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "develop"
  # Enable version updates for docker images 
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "develop"
