apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: "traefik"
    kubernetes.io/ingress.allow-http: "false"    
    traefik.ingress.kubernetes.io/redirect-entry-point: https
    traefik.ingress.kubernetes.io/redirect-permanent: "true"
    traefik.ingress.kubernetes.io/rule-type: "PathPrefixStrip"
    cert-manager.io/cluster-issuer: wildcard-issuer
  name: nm-api-ingress
  namespace: netmaker
spec:
  rules:
  - host: api.test.netmaker.org
    http:
      paths:
      - path: /
        backend:
          serviceName: netmaker
          servicePort: 8081
  tls:
  - hosts: 
    - api.test.netmaker.org
    secretName: cert-nm-api
