apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: {{ include "netmaker.fullname" . }}
  name: {{ include "netmaker.fullname" . }}
spec:
  replicas: {{ .Values.replicas }}
  serviceName: {{ include "netmaker.fullname" . }}-headless
  selector:
    matchLabels:
      app: {{ include "netmaker.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "netmaker.fullname" . }}
    spec:
      {{- if .Values.wireguard.enabled }}
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - {{ include "netmaker.fullname" . }}
            topologyKey: "kubernetes.io/hostname"
      {{- end }}
      containers:
      - env:
        - name: SERVER_API_CONN_STRING
          value: api.{{ required "A valid .Values.baseDomain entry required!" .Values.baseDomain}}:443
        - name: SERVER_GRPC_CONN_STRING
          value: grpc.{{ required "A valid .Values.baseDomain entry required!" .Values.baseDomain}}:443
        - name: GRPC_SSL
          value: "on"
        - name: SERVER_HTTP_HOST
          value: api.{{ required "A valid .Values.baseDomain entry required!" .Values.baseDomain}}
        - name: SERVER_GRPC_HOST
          value: grpc.{{ required "A valid .Values.baseDomain entry required!" .Values.baseDomain}}
        - name: API_PORT
          value: "8081"
        {{- if not .Values.wireguard.kernel }}
        - name: WG_QUICK_USERSPACE_IMPLEMENTATION
          value: wireguard-go
        {{- end }}
        - name: GRPC_PORT
          value: "443"
        {{- if .Values.dns.enabled }}
        - name: DNS_MODE
          value: "on"
        - name: COREDNS_ADDR
          value: {{ required "A valid .Values.dns.clusterIP entry required! Choose an IP from your k8s service IP CIDR" .Values.dns.clusterIP }}
        {{- else }}
        - name: DNS_MODE
          value: "off"
        {{- end }}
        {{- if .Values.wireguard.enabled }}
        - name: CLIENT_MODE
          value: "on"
        {{- else }}
        - name: CLIENT_MODE
          value: "off"
        {{- end }}
        - name: MASTER_KEY
          value: {{ include "netmaker.masterKey" . }}
        - name: PLATFORM
          value: Kubernetes
        - name: CORS_ALLOWED_ORIGIN
          value: '*'
        - name: NODE_ID
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: SQL_HOST
          value: '{{ .Release.Name }}-postgresql-ha-pgpool.{{ .Release.Namespace }}.svc.cluster.local'
        - name: SQL_PORT
          value: "5432"
        - name: SQL_DB
          value: {{ index .Values "postgresql-ha" "postgresql" "database" }}
        - name: SQL_USER
          value: {{ index .Values "postgresql-ha" "postgresql" "username" }}
        - name: SQL_PASS
          value: {{ index .Values "postgresql-ha" "postgresql" "password" }}
        - name: DATABASE
          value: postgres
      {{- if or (not .Values.wireguard.enabled) (.Values.wireguard.kernel) }}
        image: gravitl/netmaker:v0.8.4
      {{- else }}
        image: gravitl/netmaker:v0.8.4-userspace
      {{- end }}
        imagePullPolicy: Always
        name: {{ include "netmaker.fullname" . }}
        ports:
        - containerPort: 8081
          protocol: TCP
        - containerPort: 443
          protocol: TCP
        resources: {}
        {{- if .Values.wireguard.enabled }}
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
        {{- end }}
      {{- if .Values.dns.enabled }}
        volumeMounts:
        - name: {{ include "netmaker.fullname" . }}-dns-pvc
          mountPath: /root/config/dnsconfig
      volumes:
      - name: {{ include "netmaker.fullname" . }}-dns-pvc
        persistentVolumeClaim:
          claimName: {{ include "netmaker.fullname" . }}-dns-pvc
      {{- end }}