---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: netmaker-ui
spec:
  replicas: 2
  selector:
    matchLabels:
      app: netmaker-ui
  template:
    metadata:
      labels:
        app: netmaker-ui
    spec:
      containers:
      - name: netmaker-ui
        image: gravitl/netmaker-ui:v0.15.1
        ports:
        - containerPort: 443
        env:
        - name: BACKEND_URL
          value: 'https://api.NETMAKER_SUBDOMAIN'
      terminationGracePeriodSeconds: 15
---
apiVersion: v1
kind: Service
metadata:
  name: 'netmaker-ui'
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: 'netmaker-ui'
  sessionAffinity: None
  type: 'ClusterIP'
# ---
# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: nm-ui-ingress-nginx
#   annotations:
#     nginx.ingress.kubernetes.io/rewrite-target: /
#     cert-manager.io/cluster-issuer: "letsencrypt-nginx"
#     nginx.ingress.kubernetes.io/ssl-redirect: 'true'
# spec:
#   ingressClassName: nginx
#   tls:
#   - hosts:
#     - dashboard.NETMAKER_SUBDOMAIN
#     secretName: nm-ui-tls
#   rules:
#   - host: dashboard.NETMAKER_SUBDOMAIN
#     http:
#       paths:
#       - path: /
#         pathType: Prefix
#         backend:
#           service:
#             name: netmaker-ui
#             port:
#               number: 80