server:
  host: "localhost"
  apiport: "8081"
  masterkey: ""
  allowedorigin: "*"
  restbackend: true            
  agentbackend: true
  defaultnetname: "default"
  defaultnetrange: "10.10.10.0/24"
  createdefault: true